{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sim-{{ $name }}-scheme-adapter
  labels:
    app: sim-{{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  CACHE_HOST: {{ printf "sim-%s-cache" $name | quote }}
  {{- range $k, $v := $config.config.schemeAdapter.env }}
  {{ $k }}: {{ $v | quote }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sim-{{ $name }}-backend
  labels:
    app: sim-{{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{- range $k, $v := $config.config.simBackend.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
