{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mojaloop-simulator.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "mojaloop-simulator.name" . }}
    chart: {{ template "mojaloop-simulator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /{{ $fullName }}/dfsp
          backend:
            serviceName: {{ $fullName }}-sim
            servicePort: inboundapi
        - path: /{{ $fullName }}/test
          backend:
            serviceName: {{ $fullName }}-sim
            servicePort: testapi
{{- end }}
